ckpt: intfloat/e5-base
dataset: hate-speech # can be 'hate-speech', 'sentiment', 'ten-dim'
use_augmented_data: True
sampling: balanced # can be proportional or balanced
augmentation_model: gpt-4 # can be gpt-3.5-turbo or gpt-4
wandb_project: crowdsourced_vs_gpt_datasize
wandb_entity: cocoons
batch_size: 32
lr: 2e-5
num_epochs: 10
weight_decay: 0
